backend:
  name: github
  repo: Beninigmal/portifolio-fotografia
  branch: main
  auth_scope: repo
  app_id: "Ov23liFA6Y5cZfUwfqzT"
  commit_messages:
   create: "Criar {{collection}} '{{slug}}'"
   update: "Atualizar {{collection}} '{{slug}}'"

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "Portfólio"
    folder: "src/data/portfolio"
    create: true
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "photo", label: "Foto", widget: "image" }
      - { name: "description", label: "Descrição", widget: "text" }
